import{useState}from"react";import type{CartItem}from"../types";
interface Props{items:CartItem[];onBack:()=>void;onSubmit:(d:OrderData)=>void}
export interface OrderData{name:string;phone:string;email:string;address:string;payment:"card"|"cash"|"sbp";comment:string}
export default function CheckoutScreen({items,onBack,onSubmit}:Props){
const[form,setForm]=useState<OrderData>({name:"",phone:"",email:"",address:"",payment:"card",comment:""});
const[focus,setFocus]=useState<string|null>(null);
const total=items.reduce((s,i)=>s+i.price*i.qty,0);
const konEarn=items.length*10;
const handleSubmit=(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.phone.trim()){alert("Заполните имя и телефон");return;}onSubmit(form);};
const inp=(f:string):React.CSSProperties=>({padding:"14px 16px",borderRadius:12,border:`1px solid ${focus===f?"rgba(120,170,255,0.5)":"rgba(120,170,255,0.15)"}`,background:"rgba(255,255,255,0.04)",color:"#fff",fontSize:15,outline:"none",fontFamily:"inherit",width:"100%",boxSizing:"border-box",transition:"all .25s",boxShadow:focus===f?"0 0 0 3px rgba(42,111,214,0.15)":"none",transform:focus===f?"translateY(-1px)":"none"});
const pay=[{id:"card"as const,l:"Банковская карта",i:"💳",d:"Visa, Mastercard, МИР"},{id:"sbp"as const,l:"СБП (без комиссии)",i:"📱",d:"Быстрый перевод по номеру"},{id:"cash"as const,l:"Наличные при получении",i:"💵",d:"Оплата в магазине или курьеру"}];
return(<div><header className="sr-header"><button className="sr-header__back" onClick={onBack}>← Назад</button><div className="sr-header__title">Оформление заказа</div><div style={{width:60}}/></header><div className="sr-container"><div style={{background:"linear-gradient(135deg,rgba(42,111,214,0.25),rgba(61,189,224,0.15))",borderRadius:20,padding:20,marginBottom:24,border:"1px solid rgba(120,170,255,0.2)"}}><div style={{fontSize:14,color:"rgba(200,225,255,0.8)",marginBottom:10,fontWeight:600}}>Состав заказа</div>{items.map(i=>(<div key={i.id} style={{display:"flex",justifyContent:"space-between",fontSize:14,marginBottom:8,color:"#fff",alignItems:"center"}}><span style={{display:"flex",alignItems:"center",gap:8}}><span style={{background:"rgba(42,111,214,0.3)",borderRadius:8,padding:"2px 8px",fontSize:12,fontWeight:700,color:"#7cc1ff"}}>×{i.qty}</span>{i.name}</span><span style={{fontWeight:600}}>{(i.price * i.qty).toLocaleString("ru-RU")} ₽</span></div>))}<div style={{borderTop:"1px solid rgba(120,170,255,0.2)",marginTop:12,paddingTop:12,display:"flex",justifyContent:"space-between",fontWeight:800,color:"#fff",fontSize:18}}><span>Итого</span><span>{total.toLocaleString("ru-RU")} ₽</span></div><div style={{marginTop:10,fontSize:13,color:"#7cc1ff",display:"flex",alignItems:"center",gap:6}}><span>✨</span><span>+{konEarn} КОН начислится после покупки</span></div></div><form onSubmit={handleSubmit}><div className="sr-section-title"><div className="sr-section-title__icon">👤</div>Контактные данные</div><div style={{display:"flex",flexDirection:"column",gap:12,marginBottom:24}}><input type="text"placeholder="Имя и фамилия _"required value={form.name}onChange={e=>setForm({...form,name:e.target.value})}onFocus={()=>setFocus("name")}onBlur={()=>setFocus(null)}style={inp("name")}/><input type="tel"placeholder="Телефон *"required value={form.phone}onChange={e=>setForm({...form,phone:e.target.value})}onFocus={()=>setFocus("phone")}onBlur={()=>setFocus(null
)}style={inp("phone")}/><input type="email"placeholder="Email"value={form.email}onChange={e=>setForm({...form,email:e.target.value})}onFocus={()=>setFocus("email")}onBlur={()=>setFocus(null)}style={inp("email")}/><input type="text"placeholder="Адрес доставки или самовывоза"value={form.address}onChange={e=>setForm({...form,address:e.target.value})}onFocus={()=>setFocus("addr")}onBlur={()=>setFocus(null)}style={inp("addr")}/></div><div className="sr-section-title"><div className="sr-section-title__icon">💳</div>Способ оплаты</div><div style={{display:"flex",flexDirection:"column",gap:10,marginBottom:24}}>{pay.map(m=>(<label key={m.id}style={{display:"flex",alignItems:"center",gap:14,padding:16,borderRadius:14,background:form.payment===m.id?"rgba(42,111,214,0.2)":"rgba(255,255,255,0.03)",border:`1.5px solid ${form.payment===m.id?"rgba(120,170,255,0.5)":"rgba(120,170,255,0.1)"}`,cursor:"pointer",transition:"all .2s",transform:form.payment===m.id?"scale(1.01)":"scale(1)"}}><input type="radio"name="payment"checked={form.payment===m.id}onChange={()=>setForm({...form,payment:m.id})}style={{width:20,height:20,accentColor:"#2a6fd6",cursor:"pointer"}}/><span style={{fontSize:24,filter:form.payment===m.id?"none":"grayscale(0.3)"}}>{m.i}</span><div style={{flex:1}}><div style={{fontSize:15,color:"#fff",fontWeight:700}}>{m.l}</div><div style={{fontSize:12,color:"rgba(200,225,255,0.6)",marginTop:2}}>{m.d}</div></div>{form.payment===m.id&&<span style={{color:"#7cc1ff",fontSize:18}}>✓</span>}</label>))}</div><div className="sr-section-title"><div className="sr-section-title__icon">📝</div>Комментарий</div><textarea placeholder="Пожелания по доставке, удобное время звонка..."value={form.comment}onChange={e=>setForm({...form,comment:e.target.value})}onFocus={()=>setFocus("comm")}onBlur={()=>setFocus(null)}rows={3}style={{...inp("comm"),resize:"none",lineHeight:1.5}}/>

<button type="submit"className="sr-btn sr-btn--primary"style={{marginTop:28,width:"100%",padding:"16px",fontSize:16,fontWeight:700,boxShadow:"0 4px 20px rgba(42,111,214,0.3)",transition:"all .2s"}}onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-2px)";e.currentTarget.style.boxShadow="0 6px 24px rgba(42,111,214,0.4)";}}onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="0 4px 20px rgba(42,111,214,0.3)";}}>Подтвердить заказ</button><div style={{textAlign:"center",marginTop:14,fontSize:12,color:"rgba(140,170,210,0.5)",lineHeight:1.5}}>Менеджер перезвонит для подтверждения в течение 30 минут<br/>Работаем ежедневно с 9:00 до 20:00</div></form></div></div>);}
