import type { Product, LevelInfo } from "./types";

export const KON_TO_RUB = 12.9;

export const LEVELS: LevelInfo[] = [
  {
    id: "bronze",
    name: "Бронза",
    cashbackPct: 2,
    threshold: 0,
    color: "#CD7F32",
    emoji: "🥉",
  },
  {
    id: "silver",
    name: "Серебро",
    cashbackPct: 3,
    threshold: 500,
    color: "#C0C0C0",
    emoji: "🥈",
  },
  {
    id: "gold",
    name: "Золото",
    cashbackPct: 5,
    threshold: 2000,
    color: "#FFD700",
    emoji: "🥇",
  },
  {
    id: "platinum",
    name: "Платина",
    cashbackPct: 7,
    threshold: 5000,
    color: "#E5E4E2",
    emoji: "💎",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "espresso",
    name: "Эспрессо",
    description: "Классический крепкий эспрессо из отборной арабики",
    priceRub: 150,
    priceKon: 11.6,
    category: "coffee",
    emoji: "☕",
    gradient: "from-amber-900 to-amber-700",
  },
  {
    id: "cappuccino",
    name: "Капучино",
    description: "Эспрессо с нежной молочной пенкой и какао",
    priceRub: 220,
    priceKon: 17.0,
    category: "coffee",
    emoji: "☕",
    gradient: "from-amber-800 to-orange-700",
  },
  {
    id: "latte",
    name: "Латте",
    description: "Мягкий кофе с молоком и воздушной пенкой",
    priceRub: 250,
    priceKon: 19.4,
    category: "coffee",
    emoji: "🥛",
    gradient: "from-orange-700 to-amber-600",
  },
  {
    id: "raf",
    name: "Раф классический",
    description: "Нежный кофе со сливками и ванильным сахаром",
    priceRub: 290,
    priceKon: 22.5,
    category: "coffee",
    emoji: "☕",
    gradient: "from-amber-700 to-yellow-700",
  },
  {
    id: "flat-white",
    name: "Флэт уайт",
    description: "Двойной эспрессо с молоком, без пенки",
    priceRub: 270,
    priceKon: 20.9,
    category: "coffee",
    emoji: "☕",
    gradient: "from-orange-800 to-amber-700",
  },
  {
    id: "matcha",
    name: "Матча латте",
    description: "Японский зелёный чай матча с молоком",
    priceRub: 320,
    priceKon: 24.8,
    category: "tea",
    emoji: "🍵",
    gradient: "from-green-700 to-emerald-600",
  },
  {
    id: "cheesecake",
    name: "Чизкейк Нью-Йорк",
    description: "Классический чизкейк со сливочным сыром",
    priceRub: 380,
    priceKon: 29.5,
    category: "desserts",
    emoji: "🍰",
    gradient: "from-yellow-600 to-amber-500",
  },
  {
    id: "brownie",
    name: "Брауни шоколадный",
description: "Влажный шоколадный брауни с орехами",
    priceRub: 280,
    priceKon: 21.7,
    category: "desserts",
    emoji: "🍫",
    gradient: "from-stone-800 to-amber-900",
  },
  {
    id: "croissant",
    name: "Круассан с миндалём",
    description: "Слоёный круассан с миндальным кремом",
    priceRub: 220,
    priceKon: 17.0,
    category: "bakery",
    emoji: "🥐",
    gradient: "from-yellow-700 to-amber-600",
  },
  {
    id: "sandwich",
    name: "Сэндвич с курицей",
    description: "Свежий сэндвич с курицей, овощами и соусом",
    priceRub: 350,
    priceKon: 27.1,
    category: "food",
    emoji: "🥪",
    gradient: "from-orange-600 to-red-600",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  coffee: "Кофе",
  tea: "Чай",
  desserts: "Десерты",
  bakery: "Выпечка",
  food: "Еда",
};
